name: learn_clean_architecture
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  awesome_dio_interceptor: ^1.2.0
  cupertino_icons: ^1.0.6
  dio: ^5.6.0
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.8
  get: 4.6.6
  get_storage: ^2.1.1
  google_fonts: null
  image_picker: ^1.1.2
  intl: ^0.19.0
  sizer: ^2.0.15

dev_dependencies:
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
